twitter:
  outputs:
    fct:
      dataset: fct
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('GOOGLE_PROJECT_ID') }}"
      threads: 6
      type: bigquery
    dim:
      dataset: dim
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('GOOGLE_PROJECT_ID') }}"
      threads: 6
      type: bigquery
  target: dim